language: node_js
node_js:
- '0.10'

deploy:
  provider: npm
  email:
    secure: RvAewcYehR74SLCgKwSfKBOpnetI6gFm/vY6bjJHeH82VXIiBsLIA6TlqmzByv26doLNIVsE0vo4upPw95CFTtnO3iz8ewGbcg5P7oUDaVXLHozx+f5mgsB7Z+tdxfREGch/Mma1HBOqMLX5Ee+Ll0449XlEpUtGepHj/9RzsWZbWvm8HKWoOnAD/5W0wTAwhwReiVnga+Kn2zuS67iwfG1w4nDQ9rZSSw8wHPLLNJvpb7wLE6Idumlp8ZUc/wntSZzo6lha5HNiJRv8bsH2H7M+HwlujTOQfv23SItf/jaMp/D9Uw0fMFFFPgB6RnKiz+iWVfJ+7Jei+IBydctzHZz2sscFKPpAGzXtIjT13VcXgOzceeQ0rMNDRhXJaExgIqrrPPSUgVrTq0jjJtOv4ahaQky4uRYfwIfMjsFqNz4Be36UBsMsVOgGhhAs12Q24B61YmgCijMetk3uoXBZBR5RucbiTnSYhlFqYsnNHxTIvhLRONEWCVzNfGWT/jNTaE9I6dtHQWc0qjG4p7fXzp/SONks+UrC2u+qrH3Pazg972K7/LplgDVZR+SGY0lzTc8oiP+p69gQx3pPObhB1cSlE0XMvn05AyAgO+LBTqT63OszKGDe6lh1tYhb0/AMuwrlrM/Am9z0GDhOEXuBu9/XmMCHX3ExrbPVtoXUNaM=
  api_key:
    secure: vrZNb9TtRLLkZ73LEG4SKyUFVUZ47reoG3ugkfvF+CyQO0M3gyfNO6atAO8B77YwWZgCARbBXTAizd/In2oh9gK+STD0SdYIfu+Py2jJGKf1hDsKR2BKnNDjNVV/fVfoL42yF+L7NL/KGYpi4yduR33NEqRjmQ2/8owOjaySE08HvbTnRXBkRqguUIDqQ37g3zRdboaSYtnF9gc0H3RMs1XPKg5s2bsfnptnVM8kGBrehbFwME5ulHPRuwM2DQ3fi4//Vs6uv0h27lSK6Igv2+MSwk9PN5L+eYpNAjo3tO6W14TdPe6JIK2vcO4nwl8vx0z1Py4EBAPv8VmRVCTR+b0BPpoq/0fRDUHrZHqlMKriMGwFMMbXDarQ3MHK0kw88QrU53yOhYVF8jRxJ6acHcHlr+eC7kAPduvIsV/KOb96doIulQjeq03SVt/it9iLnA8A49Qpwsa9AKsrgG0HNihtlo+BCMSvaiUnV04C+sDGlj7HYK6ziRonjdlqo0kpy2YYbwE5+vwACaVXTnxUlJ8oXQGB1OZbpgwNHskVM3+T9sEM2nrZXnWm36NPHItDnPgP+h8y15D1Mp/yQ7DvsY1ssTTHBXwmUbuoFY1OrNEGx+yiFSbE4B9lJY7EA0TOW+zpwoKHmKjfK2iW1zZoLud2Zvodsz7FnTN6u2vySmA=
  on:
    tags: true
    branch: master
